### ISSUE TITLE
Pins - Information window

### ISSUE THREAD

**Issue by pcrossnz** [fergusfrl/RiverWiki#18] opened 2018-09-05 22:49 UTC
Can we add information windows with basic info? Maybe grade, region. Perhaps even a small picture?!

**Comment by fergusfrl** [comment] 2018-09-05 22:51
Duplicate of https://github.com/fergusfrl/RiverWiki/issues/2#issue-357391848
I'll Add as a comment in original issue

**Comment by fergusfrl** [comment] 2018-09-05 23:08
Closed as Duplicate

**Closed by fergusfrl** 2018-09-05 23:08 UTC
Labels: duplicate
